--
-- Файл сгенерирован с помощью SQLiteStudio v3.2.1 в чт окт. 8 13:33:57 2020
--
-- Использованная кодировка текста: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: event
CREATE TABLE event (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, hash TEXT UNIQUE, name STRING UNIQUE, start BIGINT, "end" BIGINT, lat REAL, lon REAL, height REAL);

-- Таблица: hv_line
CREATE TABLE hv_line (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, event INTEGER UNIQUE, hv1 INTEGER, hv2 INTEGER, hv3 INTEGER, hv4 INTEGER, hv5 INTEGER, hv6 INTEGER, hv7 INTEGER, hv8 INTEGER, hv9 INTEGER, hv10 INTEGER, hv11 INTEGER, hv12 INTEGER, hv13 INTEGER, hv14 INTEGER, hv15 INTEGER, hv16 INTEGER, hv17 INTEGER, hv18 INTEGER, hv19 INTEGER, hv20 INTEGER, hv21 INTEGER, hv22 INTEGER, hv23 INTEGER, hv24 INTEGER, hv25 INTEGER, hv26 INTEGER, hv27 INTEGER, hv28 INTEGER, hv29 INTEGER, hv30 INTEGER, hv31 INTEGER, hv32 INTEGER);

-- Таблица: line
CREATE TABLE line (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, matrix INTEGER, data_1 INTEGER, data_2 INTEGER, data_3 INTEGER, data_4 INTEGER, data_5 INTEGER, data_6 INTEGER, data_7 INTEGER, data_8 INTEGER, data_9 INTEGER, data_10 INTEGER, data_11 INTEGER, data_12 INTEGER, data_13 INTEGER, data_14 INTEGER, data_15 INTEGER, data_16 INTEGER);

-- Таблица: matrix
CREATE TABLE matrix (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, event INTEGER);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
