--
-- Файл сгенерирован с помощью SQLiteStudio v3.2.1 в сб окт. 10 12:40:53 2020
--
-- Использованная кодировка текста: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: event
DROP TABLE IF EXISTS event;
CREATE TABLE event (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, hash TEXT UNIQUE, name STRING UNIQUE, start BIGINT, "end" BIGINT, lat REAL, lon REAL, height REAL);

-- Таблица: hv_line
DROP TABLE IF EXISTS hv_line;
CREATE TABLE hv_line (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, hv1 INTEGER, hv2 INTEGER, hv3 INTEGER, hv4 INTEGER, hv5 INTEGER, hv6 INTEGER, hv7 INTEGER, hv8 INTEGER, hv9 INTEGER, hv10 INTEGER, hv11 INTEGER, hv12 INTEGER, hv13 INTEGER, hv14 INTEGER, hv15 INTEGER, hv16 INTEGER, hv17 INTEGER, hv18 INTEGER, hv19 INTEGER, hv20 INTEGER, hv21 INTEGER, hv22 INTEGER, hv23 INTEGER, hv24 INTEGER, hv25 INTEGER, hv26 INTEGER, hv27 INTEGER, hv28 INTEGER, hv29 INTEGER, hv30 INTEGER, hv31 INTEGER, hv32 INTEGER);

-- Таблица: matrix
DROP TABLE IF EXISTS matrix;
CREATE TABLE matrix (id INTEGER PRIMARY KEY ASC AUTOINCREMENT, event INTEGER, data BLOB);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
